### ISSUE TITLE
Not enough time data in road link emission files

### ISSUE THREAD

**Issue by avaldebe** [metno/uEMEP#5]
Hi Bruce,

Think I found a bug while testing the update 5 configurations for EMEP4NO:
- NORTRIP_multiroad_config_Norway_forecast_PPI_update_5.txt
- uEMEP_EMEP4NO_config_hourly_default_PPI_update_5.txt

After changing `filename_rl(2)`/`pathname_rl(2)` to match the NORTIP config, 
uemep complains there is not enough records on the road link emission file

```text
================================================================
Reading road link emission data (uEMEP_read_roadlink_emission_data)
================================================================
 Opening road link file(ascii) /lustre/storeB/project/fou/kl/emep/ModelRuns/NORTRIP/Forecast_2019/NORTRIP_out/emissions/uEMEP_emissions_all_sand_salt_2019082818.txt
 Number of road link emission compounds=            6
 Road link emission compounds= PM10            PM25            PMex            NOX             PM10_sand       PM10_salt       
 Road link emission units= g/km/hr
 Road link emission start date= 2019082818
 Number of road links=       713218
 Number of time steps=           67
 Road link emission starting date found. Index:     18
ERROR: Not enough time data in road link emission files:     50    66
```

It looks to me as if uemep found all 67 records on the road link file, but could only read 50 of the 66 records.

Runed NORTIP for 20190828 18UTC +66h, without any issues, as follows
```bash
NORTIP config 2019,08,28,18 2019,08,31,12
```

Here is the content of the extra configuration for the 18UTC uemep emission

```fortran
file_tag='Norway'
forecast_hour_str='18'
filename_EMEP(3)='meps_mbr0_extracted_2_5km_<replace_date>T18Z.nc'
! Meteo files have 66 records
start_time_meteo_nc_index=1
end_time_meteo_nc_index=66
save_emissions_start_index=1
save_emissions_end_index=66
filename_rl(2)='uEMEP_emissions_all_sand_salt_<replace_date>18.txt'
pathname_rl(2)='/lustre/storeB/project/fou/kl/emep/ModelRuns/NORTRIP/Forecast_2019/NORTRIP_out/emissions/'
```

**Comment by brucerd** [comment]
Hi Alvaro,
This is probably due to the time index used in uEMEP. When it reads EMEP it takes the time stamp from there. Previously we skipped over a day and started reading at hour 25, or somehting like that. Does EMEP now start without the spinnup hours? In that case setting the 
	start_time_nc_index=1
	end_time_nc_index=66 or 60
in uEMEP should fix it, I would think.

Bruce

**Comment by avaldebe** [comment]
> This is probably due to the time index used in uEMEP. When it reads EMEP it takes the time stamp from there. Previously we skipped over a day and started reading at hour 25, or something like that. 
> Does EMEP now start without the spinnup hours?

Need uEMEP emissions of the correct length to run the model. So I do not have a EMEP result without spinnup.

> In that case setting the
start_time_nc_index=1
end_time_nc_index=66 or 60
in uEMEP should fix it, I would think.

Did not work.

New 18UTC config

```fortran
file_tag='Norway'
forecast_hour_str='18'
filename_EMEP(3)='meps_mbr0_extracted_2_5km_<replace_date>T18Z.nc'
pathname_rl(2)='/lustre/storeB/project/fou/kl/emep/ModelRuns/NORTRIP/Forecast_2019/NORTRIP_out/emissions/'
filename_rl(2)='uEMEP_emissions_all_sand_salt_<replace_date>18.txt'
! Meteo files have 66 records, process them all
start_time_meteo_nc_index=1
end_time_meteo_nc_index=66
start_time_nc_index=1
end_time_nc_index=66
save_emissions_start_index=1
save_emissions_end_index=66
```
same error

```text
================================================================
Reading road link emission data (uEMEP_read_roadlink_emission_data)
================================================================
 Opening road link file(ascii) /lustre/storeB/project/fou/kl/emep/ModelRuns/NORTRIP/Forecast_2019/NORTRIP_out/emissions/uEMEP_emissions_all_sand_salt_2019082818.txt
 Number of road link emission compounds=            6
 Road link emission compounds= PM10            PM25            PMex            NOX             PM10_sand       PM10_salt       
 Road link emission units= g/km/hr
 Road link emission start date= 2019082818
 Number of road links=       713218
 Number of time steps=           67
 Road link emission starting date found. Index:     18
ERROR: Not enough time data in road link emission files:     50    66
```

**Comment by avaldebe** [comment]
> > This is probably due to the time index used in uEMEP. When it reads EMEP it takes the time stamp from there. Previously we skipped over a day and started reading at hour 25, or something like that.
> > Does EMEP now start without the spinnup hours?
> 
> Need uEMEP emissions of the correct length to run the model. So I do not have a EMEP result without spinnup.

If there is no way around this circular dependency, I'll have to disable the uemep emissions and run the model without them, and enable them when we run 00/06/12UTC +60h without spin-up.

**Comment by brucerd** [comment]
Alvaro,
I have fixed quite a few things recently and have a long list of files to update. Only 2 of these are in principle relevant for our current problem. Do you want me to submitt only those two and wait with the others or can I do them all now? I don't think it is a problem if you actually take the entire set. Everything is working and should work on old configs as well.

Bruce

**Comment by brucerd** [comment]
Hi Alvaro,
I need to submitt all I have because I need to run on the new stuff. The two files that I have changed because of this particular problem are:

uEMEP_save_emission_netcdf.f90
uEMEP_read_time_profiles.f90

Commit message
[master 5da21bf] Inclusion  of surface ozone reading, changes that fixed the emission writing routines for any hour, fixed time profile reading bug, various fixes in the deposition routines
 13 files changed, 175 insertions(+), 127 deletions(-)

Push message
Counting objects: 15, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (15/15), done.
Writing objects: 100% (15/15), 3.27 KiB | 1.64 MiB/s, done.
Total 15 (delta 14), reused 0 (delta 0)
remote: Resolving deltas: 100% (14/14), completed with 14 local objects.
To https://github.com/metno/uEMEP.git
   0470d08..5da21bf  master -> master


Below is my testing of the changes:

Made this call to NORTRIP
 .\uEMEP\NORTRIP_multiroad_combined\Fortran\binary\NORTRIP_multiroad_combined_v2.exe .\uEMEP\NORTRIP_Norway\config\NORTRIP_multiroad_config_Norway.txt 2019,08,29,19 2019,09,01,12

Produced an emissions file with 66 hours of data called
uEMEP_emissions_all_sand_salt_2019082919.txt


Made this call to uEMEP 
.\uEMEP_v4.1.exe .\config\uEMEP_EMEP4NO_config_hourly_deposition_testing2_emissions.txt 2019082919

Produced an emissions file with 66 hours of data called
uEMEP_emission_for_EMEP_test_traffic_all_sand_salt_2019082919.nc

Have taken away the standard 'hour_str' from the emission files

relevant change in code is in these two files
uEMEP_save_emission_netcdf.f90
uEMEP_read_time_profiles.f90

Before in uEMEP_save_emission_netcdf:
    format_temp='yyyymmdd'
    call datestr_to_date(config_date_str,format_temp,a_start)
    !Assumes it starts at hour 1
    a_start(4)=1
After in uEMEP_save_emission_netcdf:
    format_temp='yyyymmddHH'
    call datestr_to_date(config_date_str,format_temp,a_start)
    !Assumes it starts at hour 1
    !a_start(4)=1
    !Do not assume it starts at hour 1 any more

And also took away the hour_str in the emissions output file since it uses the emission date_str in its entirety
Also put in an allocation that was missing 
Also fixed a bug in the read_time_profiles_routine that caused problems when the wood burning files were not read

Tested for all 4 hours of the day 01,07,13,19

In config file used:
	start_time_nc_index=1
	end_time_nc_index=66
	save_emissions_start_index=1
	save_emissions_end_index=66
    start_time_meteo_nc_index=2
    end_time_meteo_nc_index=67

Note that the meteo starts at 2 because the first hour is 18 in the meteo files
If EMEP starts at 18 then you will also have to write
	start_time_nc_index=2
	end_time_nc_index=67
	
when doing the normal tile and station calculations

Also note need to set
	forecast_hour_str='18'
	filename_EMEP(3)='meps_mbr0_extracted_2_5km_<yyyymmdd>T<replace_hour>Z.nc'

**Comment by avaldebe** [comment]
after pulling all the changes I get the following error from `make`

```text
uEMEP_control_v2.o: In function `MAIN__':
/home/alvarov/uEMEP/uEMEP/uEMEP_control_v2.f90:200: undefined reference to `uemep_read_landuse_rivm_data_'
/home/alvarov/uEMEP/uEMEP/uEMEP_control_v2.f90:252: undefined reference to `uemep_set_deposition_velocities_'
/home/alvarov/uEMEP/uEMEP/uEMEP_control_v2.f90:285: undefined reference to `uemep_subgrid_deposition_emep_'
/home/alvarov/uEMEP/uEMEP/uEMEP_control_v2.f90:307: undefined reference to `uemep_calculate_deposition_'
/home/alvarov/uEMEP/uEMEP/uEMEP_control_v2.f90:266: undefined reference to `uemep_subgrid_deposition_'
```

**Comment by avaldebe** [comment]
```text
================================================================
Reading time profiles (uEMEP_read_time_profiles)
================================================================
 Opening time profile file: /modules/centos7/user-apps/uemep/201908/share/data/Time_Variation_v1.csv
 Number of columns read:            5
 uEMEP_source_index           2           3           4           6
Region        1100
Hour_of_week         168
Month_of_year          12
Date array start =   2019     8    28    19     0     0
 Emission profiles set to summer time. 
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
uEMEP              00000000005AAE6D  for__signal_handl     Unknown  Unknown
libpthread-2.17.s  00002B17A68425D0  Unknown               Unknown  Unknown
uEMEP              00000000004CD0A0  Unknown               Unknown  Unknown
uEMEP              00000000005727F7  Unknown               Unknown  Unknown
uEMEP              0000000000452C23  Unknown               Unknown  Unknown
uEMEP              000000000040AADE  Unknown               Unknown  Unknown
libc-2.17.so       00002B17A6A71495  __libc_start_main     Unknown  Unknown
uEMEP              000000000040A9E9  Unknown               Unknown  Unknown
```

**Comment by avaldebe** [comment]
Better, but now crash out of missing complementary meteo
```text
================================================================
Reading additional meteo data (uEMEP_read_meteo_nc)
================================================================
 Surface level base set to:            1
 WARNING: Meteo netcdf file does not exist: /lustre/storeB/project/metproduction/products/meps/member_0/meps_mbr0_extracted_2_5km_20190828T18Z.nc
 Will try 6 hours before 4 times
 Trying: /lustre/storeB/project/metproduction/products/meps/member_0/meps_mbr0_extracted_2_5km_20190827T18Z.nc
 Trying: /lustre/storeB/project/metproduction/products/meps/member_0/meps_mbr0_extracted_2_5km_20190827T12Z.nc
 Trying: /lustre/storeB/project/metproduction/products/meps/member_0/meps_mbr0_extracted_2_5km_20190827T06Z.nc
 Trying: /lustre/storeB/project/metproduction/products/meps/member_0/meps_mbr0_extracted_2_5km_20190827T00Z.nc
 ERROR: Meteo netcdf file still does not exist: /lustre/storeB/project/metproduction/products/meps/member_0/meps_mbr0_extracted_2_5km_20190827T00Z.nc
 STOPPING
```

**Comment by avaldebe** [comment]
The program is now runs all the way trough. Just need better control over the output names, but that is another issue.

1e3 thanks
